# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c6c56771dfe9076ba26c9911d7368a84d21e0e3e33e794a2c1a1170cffae93c74152e12b9fdf07dc77292b753724e9504d425ff41614f4a765348af70766fb4

test:
  secret_key_base: 2bab77de50d0eb1de836a424316fa8de7d38b5f6c3e0ce9e9ee146245c1cbeadce84438c498b8c12a18354802b5d76e789983c12bce6509afa14671e3ba16109

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
